### ISSUE TITLE
Graph limitation for daily state plot 

### ISSUE THREAD

**Issue by Abdelmouise** [AshtonIzmev/covid-19-pandemic-simulation#4]
Hi Issam,
i apply the command "python -m simulator.run --population-state --nday 150 " to plot the daily state(i'm working on build_individual_houses_map ) i have as a result the attached plot, i think that the graph is limited in y-axis. 
![daily_cases](https://user-images.githubusercontent.com/55956954/79699150-e445ca00-828d-11ea-8ec0-f09cf576e2b8.PNG)

**Comment by AshtonIzmev** [comment]
Hi Abdelmouise, thanks for raising the issue.
Default population is 1000 so the y-axis should be limited to 1000. Is there something incorrect with that ?
It goes to 2000 with 
`python -m simulator.run --population-state --nday 15 --nind 2000`

**Comment by Abdelmouise** [comment]
Because at the begning the number was 5000, I actually set the number to 5000, but the shape of the curve that I find is totally different (please see it below )than that in Readme
![daily_cases_5000](https://user-images.githubusercontent.com/55956954/79700579-fc6e1700-8296-11ea-9d9f-c6987c4b59fb.PNG)
Do you get the same plot with 5000 ?

**Comment by AshtonIzmev** [comment]
True. I tweaked the default parameters a few times. I'll refactor the parameters.py file into more readable and smaller pieces and then freeze the default behavior.

**Comment by Abdelmouise** [comment]
Thanks for the information. 
BTW I modified the "build_individual_houses_map" function and I also modified the initiator_test, I still have to modify simulator_test (a lot of values should be modified
 in simulator_test )

**Comment by AshtonIzmev** [comment]
Ok thanks. I'll close this issue then.

**Comment by AshtonIzmev** [comment]
To let you know, I broke the draw parameter method in commit 96a08d31b7ce35c.
Please use --draw pop for example instead of --population-state
