### ISSUE TITLE
Question & Proposition 

### ISSUE THREAD

**Issue by Abdelmouise** [AshtonIzmev/covid-19-pandemic-simulation#6]
Hi Issam,
I'm sorry to ask you this question in issue format (I couldn't find any other way to contact you).
I just have a question about the latest changes on "weighted behavior". does this concern the following story :  "Use a contagion probability model for each individual"? 
because I'm trying to understand these last modifications and I wanted to know the context first to easily understand the idea.

And I also have a proposal that we can add. since this algorithm models individuals, so it might be interesting to add a "deconfinement"  protocol, for example a test and isolation strategy. I explain, we can say that at the end of confinement, each sympthomatic person will be tested and also the  members of his family, then  eache positive person  will be isolated or hospitalized (in any case he can not infect anyone). 
I preferred  to not write this in the backloc because it might be out of  scop of this study.
What do you think?

**Comment by AshtonIzmev** [comment]
Hi Abdelmouise, yes this weighted behavior is the individual behavior dictionnary. I'll update the README. Every person has weights that can make the global lockdown values change slightly. I wanted to see the impact of a whole neighborhood (block) not following lockdown rules (it will be a scenario). 

About your idea, it is a good one. Here is how I would see it :
So if a person is hospitalized (there others can be considered asymptomatic), there is a "test-isolation protocol" probability for each person he infected to be tested and then we make those persons isolated (no store, no work). It seems some changes are needed but definitely possible.

With probability 0 of test-isolation protocol, the current behavior should hold.

Good for backlog to me. You take it ?

**Comment by Abdelmouise** [comment]
I added it to the backlog, Yes i'll strat working on it

**Comment by Abdelmouise** [comment]
Hi Issam,
could you please add another branch, in which i push my commits? because the story of "test-isolation strategy needs a lot fo changes"   so I would like to push the changes even if they are incomplete, so you can follow  what i have done, and adapt the code as things progress without changing the Master branch.

**Comment by AshtonIzmev** [comment]
Hi Abdelmouise, sure. I created a test-isolation-feature branch.
Can't wait to see the new feature.
Issam
